
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=FALSE
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  freemarker:
    suffix:
    template-loader-path: