
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=FALSE
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/
mybatis:
  mapper-locations: classpath:mapper