server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=FALSE
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  mvc:
    view:
      suffix: .html
      prefix:
mybatis:
  mapper-locations: classpath:mapper